image: python:3.8

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install .[dev]

stages:
  - lint
  - test

linting:
  stage: lint
  script:
    - tox -e lint
    - tox -e type

unit-tests:
  stage: test
  script: tox -e unit_test

integration-tests:
  stage: test
  script:
    - tox -e integration_test
