image: python:3.8

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install .

stages:
  - test

test-job:
  stage: test
  script:
    - python -m unittest discover -s inference_tools_test
