image: python:3.8

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install .[dev]

stages:
  - lint
  - test

linting:
  stage: lint
  script: flake8 inference_tools

unit-tests:
  stage: test
  script:
    - pytest -v --cov=inference_tools inference_tools_test/unit
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

integration-tests:
  stage: test
  script:
    - echo $SERVICE_ACCOUNT_USERNAME
    - pytest -v --cov=inference_tools --username=$SERVICE_ACCOUNT_USERNAME --password=$SERVICE_ACCOUNT_PASSWORD --token=$TOKEN  inference_tools_test/integration
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'