from enum import Enum


class Step(Enum):
    SAVE_MODEL = 1
    REGISTER_MODEL = 2
    REGISTER_EMBEDDINGS = 3
    REGISTER_SIMILARITY_VIEW = 4
    REGISTER_NON_BOOSTED_STATS = 5
    REGISTER_BOOSTING_FACTORS = 6
    REGISTER_BOOSTING_VIEW = 7
    REGISTER_BOOSTED_STATS = 8
    REGISTER_STATS_VIEW = 9
